---
name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo login
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo login
      - name: Check for updates
        run: make
      - name: Push
        id: push
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        # ID from https://api.github.com/users/authentik-automation[bot]
        run: |
          git config --global user.email "135050075+authentik-automation[bot]@users.noreply.github.com"
          git config --global user.name "authentik-automation[bot]"
          version=$(cd version && cargo run)
          sed -i -e "s/^version.*/version = \"${version}\"/" Cargo.toml
          git add .
          git commit -F "diff.test" || exit 0
          git push
          git tag $version
          git push --tags
          cargo publish
          gh release create $version -F diff.test
